services:
  plant-backend:
    image: ghcr.io/boredhero/plant-backend:latest
    build: .
    network_mode: host
    restart: always
    env_file: .env
    volumes:
      - /home/noah/plantcam-data:/app/data
      - /var/www/planting.martinospizza.dev/cam:/app/cam1:ro
      - /var/www/planting.martinospizza.dev/cam2:/app/cam2:ro
    environment:
      - DATA_DIR=/app/data
      - HLS_DIR=/app/cam1/hls
      - CAM1_HLS_DIR=/app/cam1/hls
      - CAM2_HLS_DIR=/app/cam2/hls
      - TZ=America/New_York
